# Generated by Django 4.2.2 on 2023-07-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='donor_id',
        ),
    ]
