# Generated by Django 4.2.2 on 2023-07-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearby_hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpacket',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A positive'), ('A-', 'A negative'), ('B+', 'B positive'), ('B-', 'B negative'), ('AB+', 'AB postive'), ('AB-', 'AB negative'), ('O+', 'O positive'), ('O-', 'O negative')], max_length=400),
        ),
    ]
