# Generated by Django 4.2.2 on 2023-07-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearby_hospitals', '0002_alter_bloodpacket_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpacket',
            name='units_available',
            field=models.IntegerField(),
        ),
    ]
